ISO27001_CONTROLS = [
    # Administrative
    ("A.5.1",  "Information Security Policies",             "Administrative", True,  2.0),
    ("A.5.2",  "Information Security Roles & Responsibilities", "Administrative", True, 2.0),
    ("A.6.1",  "Internal Organization",                    "Administrative", False, 1.0),
    ("A.6.2",  "Mobile Devices & Teleworking",             "Administrative", False, 1.0),
    ("A.7.1",  "Human Resource Security – Prior Employment","Administrative", False, 1.0),
    ("A.7.2",  "During Employment",                        "Administrative", False, 1.0),
    ("A.7.3",  "Termination & Change of Employment",       "Administrative", False, 1.0),
    ("A.8.1",  "Responsibility for Assets",                "Administrative", False, 1.5),
    ("A.8.2",  "Information Classification",               "Administrative", True,  1.5),
    ("A.8.3",  "Media Handling",                           "Administrative", False, 1.0),
    ("A.9.1",  "Business Requirements of Access Control",  "Administrative", True,  2.0),
    ("A.9.2",  "User Access Management",                   "Administrative", True,  2.0),
    ("A.9.3",  "User Responsibilities",                    "Administrative", False, 1.0),
    ("A.18.1", "Compliance with Legal Requirements",       "Administrative", True,  2.0),
    ("A.18.2", "Information Security Reviews",             "Administrative", False, 1.5),
    # Technical
    ("A.9.4",  "System & Application Access Control",      "Technical", True,  2.0),
    ("A.10.1", "Cryptographic Controls",                   "Technical", True,  2.0),
    ("A.12.1", "Operational Procedures & Responsibilities","Technical", False, 1.5),
    ("A.12.2", "Protection from Malware",                  "Technical", True,  2.0),
    ("A.12.3", "Backup",                                   "Technical", True,  2.0),
    ("A.12.4", "Logging & Monitoring",                     "Technical", True,  2.0),
    ("A.12.5", "Control of Operational Software",          "Technical", False, 1.5),
    ("A.12.6", "Technical Vulnerability Management",       "Technical", True,  2.0),
    ("A.13.1", "Network Security Management",              "Technical", True,  2.0),
    ("A.13.2", "Information Transfer",                     "Technical", False, 1.5),
    ("A.14.1", "Security Requirements of Information Systems","Technical", True, 2.0),
    ("A.14.2", "Security in Development & Support",        "Technical", False, 1.5),
    ("A.14.3", "Test Data",                                "Technical", False, 1.0),
    ("A.16.1", "Management of Security Incidents",         "Technical", True,  2.0),
    ("A.17.1", "Information Security Continuity",          "Technical", True,  2.0),
    # Physical
    ("A.11.1", "Secure Areas",                             "Physical", True,  2.0),
    ("A.11.2", "Equipment Security",                       "Physical", False, 1.5),
    ("A.15.1", "Supplier Relationships – Security Policy", "Physical", False, 1.0),
    ("A.15.2", "Supplier Service Delivery Management",     "Physical", False, 1.0),
]

SOC2_CONTROLS = [
    # Administrative
    ("CC1.1", "COSO Principle 1 – Integrity & Ethical Values", "Administrative", True,  2.0),
    ("CC1.2", "Board Independence & Oversight",                "Administrative", True,  2.0),
    ("CC1.3", "Organizational Structure",                      "Administrative", False, 1.5),
    ("CC1.4", "Competence & Training",                         "Administrative", False, 1.0),
    ("CC1.5", "Accountability",                                "Administrative", False, 1.0),
    ("CC2.1", "Risk Communication",                            "Administrative", False, 1.0),
    ("CC2.2", "Internal Communication",                        "Administrative", False, 1.0),
    ("CC2.3", "External Communication",                        "Administrative", False, 1.0),
    ("CC3.1", "Risk Assessment Objectives",                    "Administrative", True,  2.0),
    ("CC3.2", "Risk Identification & Analysis",                "Administrative", True,  2.0),
    ("CC3.3", "Fraud Risk Assessment",                         "Administrative", True,  2.0),
    ("CC4.1", "Control Monitoring Activities",                 "Administrative", False, 1.5),
    ("CC4.2", "Deficiency Evaluation & Remediation",           "Administrative", False, 1.5),
    ("CC5.1", "Control Environment Selection",                 "Administrative", False, 1.0),
    ("CC5.2", "Technology Control Selection",                  "Administrative", False, 1.0),
    # Technical
    ("CC6.1", "Logical Access Security",                       "Technical", True,  2.0),
    ("CC6.2", "Authentication Prior to Access",                "Technical", True,  2.0),
    ("CC6.3", "Access Role Management",                        "Technical", True,  2.0),
    ("CC6.6", "External Threats Prevention",                   "Technical", True,  2.0),
    ("CC6.7", "Data Transmission & Mobile Device Security",    "Technical", True,  2.0),
    ("CC6.8", "Malware Prevention",                            "Technical", True,  2.0),
    ("CC7.1", "Vulnerability Detection & Management",          "Technical", True,  2.0),
    ("CC7.2", "Security Incident Monitoring",                  "Technical", True,  2.0),
    ("CC7.3", "Security Event Evaluation",                     "Technical", False, 1.5),
    ("CC7.4", "Incident Response",                             "Technical", True,  2.0),
    ("CC8.1", "Change Management Process",                     "Technical", False, 1.5),
    ("CC9.1", "Risk Mitigation",                               "Technical", False, 1.5),
    ("CC9.2", "Vendor Risk Management",                        "Technical", False, 1.5),
    ("A1.1",  "Capacity Planning",                             "Technical", False, 1.0),
    # Physical
    ("CC6.4", "Physical Access Restriction",                   "Physical", True,  2.0),
    ("CC6.5", "Physical Asset Disposal",                       "Physical", False, 1.5),
]

HIPAA_CONTROLS = [
    # Administrative
    ("164.308(a)(1)", "Security Management Process",           "Administrative", True,  2.0),
    ("164.308(a)(2)", "Assigned Security Responsibility",      "Administrative", True,  2.0),
    ("164.308(a)(3)", "Workforce Security",                    "Administrative", True,  2.0),
    ("164.308(a)(4)", "Information Access Management",         "Administrative", True,  2.0),
    ("164.308(a)(5)", "Security Awareness & Training",         "Administrative", False, 1.5),
    ("164.308(a)(6)", "Security Incident Procedures",          "Administrative", True,  2.0),
    ("164.308(a)(7)", "Contingency Plan",                      "Administrative", True,  2.0),
    ("164.308(a)(8)", "Evaluation",                            "Administrative", False, 1.5),
    ("164.308(b)(1)", "Business Associate Contracts",          "Administrative", True,  2.0),
    ("164.314(a)(1)", "Business Associate Contracts & Other",  "Administrative", False, 1.0),
    ("164.316(a)",    "Policies & Procedures",                 "Administrative", False, 1.5),
    ("164.316(b)(1)", "Documentation Requirements",            "Administrative", False, 1.0),
    # Technical
    ("164.312(a)(1)", "Access Control",                        "Technical", True,  2.0),
    ("164.312(a)(2)(i)","Unique User Identification",          "Technical", True,  2.0),
    ("164.312(a)(2)(ii)","Emergency Access Procedure",         "Technical", True,  2.0),
    ("164.312(a)(2)(iii)","Automatic Logoff",                  "Technical", False, 1.0),
    ("164.312(a)(2)(iv)","Encryption & Decryption",            "Technical", True,  2.0),
    ("164.312(b)",    "Audit Controls",                        "Technical", True,  2.0),
    ("164.312(c)(1)", "Integrity Controls",                    "Technical", True,  2.0),
    ("164.312(d)",    "Person or Entity Authentication",       "Technical", True,  2.0),
    ("164.312(e)(1)", "Transmission Security",                 "Technical", True,  2.0),
    ("164.312(e)(2)(i)","Integrity Controls – Transmission",   "Technical", False, 1.5),
    ("164.312(e)(2)(ii)","Encryption",                         "Technical", True,  2.0),
    # Physical
    ("164.310(a)(1)", "Facility Access Controls",              "Physical", True,  2.0),
    ("164.310(a)(2)(i)","Contingency Operations",              "Physical", False, 1.0),
    ("164.310(a)(2)(ii)","Facility Security Plan",             "Physical", True,  2.0),
    ("164.310(a)(2)(iii)","Access Control & Validation",       "Physical", False, 1.5),
    ("164.310(a)(2)(iv)","Maintenance Records",                "Physical", False, 1.0),
    ("164.310(b)",    "Workstation Use",                       "Physical", False, 1.0),
    ("164.310(c)",    "Workstation Security",                  "Physical", True,  2.0),
    ("164.310(d)(1)", "Device & Media Controls",               "Physical", True,  2.0),
]

DPDP_CONTROLS = [
    # Administrative
    ("DPDP-1.1",  "Data Fiduciary Obligations",               "Administrative", True,  2.0),
    ("DPDP-1.2",  "Privacy Notice",                           "Administrative", True,  2.0),
    ("DPDP-1.3",  "Purpose Limitation",                       "Administrative", True,  2.0),
    ("DPDP-1.4",  "Consent Management",                       "Administrative", True,  2.0),
    ("DPDP-1.5",  "Legitimate Uses of Data",                  "Administrative", False, 1.5),
    ("DPDP-2.1",  "Data Principal Rights Policy",             "Administrative", True,  2.0),
    ("DPDP-2.2",  "Right to Access – Implementation",         "Administrative", True,  2.0),
    ("DPDP-2.3",  "Right to Correction & Erasure",            "Administrative", True,  2.0),
    ("DPDP-2.4",  "Right to Grievance Redressal",             "Administrative", False, 1.5),
    ("DPDP-2.5",  "Right to Nominate",                        "Administrative", False, 1.0),
    ("DPDP-3.1",  "Data Protection Officer Assignment",       "Administrative", True,  2.0),
    ("DPDP-3.2",  "Data Protection Impact Assessment",        "Administrative", True,  2.0),
    ("DPDP-3.3",  "Children's Data Processing",               "Administrative", True,  2.0),
    ("DPDP-4.1",  "Data Processor Agreements",                "Administrative", False, 1.5),
    ("DPDP-4.2",  "Cross-Border Data Transfer",               "Administrative", True,  2.0),
    # Technical
    ("DPDP-5.1",  "Data Minimization Controls",               "Technical", True,  2.0),
    ("DPDP-5.2",  "Data Accuracy & Quality",                  "Technical", False, 1.5),
    ("DPDP-5.3",  "Storage Limitation & Retention Policy",    "Technical", True,  2.0),
    ("DPDP-5.4",  "Encryption of Personal Data",              "Technical", True,  2.0),
    ("DPDP-5.5",  "Access Controls for Personal Data",        "Technical", True,  2.0),
    ("DPDP-5.6",  "Audit Logs for Data Processing Activities","Technical", True,  2.0),
    ("DPDP-6.1",  "Security Breach Detection",                "Technical", True,  2.0),
    ("DPDP-6.2",  "Breach Notification to Board",             "Technical", True,  2.0),
    ("DPDP-6.3",  "Breach Notification to Data Principals",   "Technical", True,  2.0),
    ("DPDP-7.1",  "Consent Withdrawal Mechanism",             "Technical", True,  2.0),
    # Physical
    ("DPDP-8.1",  "Physical Security of Data Storage",        "Physical", True,  2.0),
    ("DPDP-8.2",  "Secure Data Disposal",                     "Physical", False, 1.5),
    ("DPDP-8.3",  "Third-Party Audit Access Control",         "Physical", False, 1.0),
]

FRAMEWORKS = [
    {
        "name": "ISO 27001",
        "description": "International standard for information security management systems (ISMS). Provides a systematic approach to managing sensitive company information.",
        "version": "ISO/IEC 27001:2022",
        "controls": ISO27001_CONTROLS,
    },
    {
        "name": "SOC 2",
        "description": "Service Organization Control 2 framework for managing customer data based on five Trust Service Criteria: security, availability, processing integrity, confidentiality, and privacy.",
        "version": "AICPA SOC 2 2017",
        "controls": SOC2_CONTROLS,
    },
    {
        "name": "HIPAA",
        "description": "Health Insurance Portability and Accountability Act. US law providing data privacy and security provisions for safeguarding medical information.",
        "version": "HIPAA Security Rule 2013",
        "controls": HIPAA_CONTROLS,
    },
    {
        "name": "DPDP",
        "description": "Digital Personal Data Protection Act (India). Governs the processing of digital personal data, establishing rights of data principals and obligations of data fiduciaries.",
        "version": "DPDP Act 2023",
        "controls": DPDP_CONTROLS,
    },
]
